### ISSUE TITLE
glfwGetX11Display error

### ISSUE THREAD

**Issue by Spaceman007** [caadxyz/glfwOcctViewer#1]
Hi, I have installed glfw3.2.1. When I  **make**, there are errors:

glfw-occt/GlfwOcctWindow.cpp:58:66: error: conversion from ‘Display* {aka _XDisplay*}’ to ‘const TCollection_AsciiString’ is **_ambiguous_**
     myDisplay = new Aspect_DisplayConnection (glfwGetX11Display());

Can someone help me with that. Thanks a lot.

**Comment by Spaceman007** [comment]
I find this works, just delete `glfwGetX11Display()` in `GlfwOcctWindow.cpp` as follows:
(I am using ubuntu18.04)

```c++
#if !defined(_WIN32) && !defined(__APPLE__)                             
  /* myDisplay = new Aspect_DisplayConnection (glfwGetX11Display()); */ 
  myDisplay = new Aspect_DisplayConnection(); 
#endif                                                                  
```

**Comment by mahaidong** [comment]
> Hi, I have installed glfw3.2.1. When I **make**, there are errors:
> 
> glfw-occt/GlfwOcctWindow.cpp:58:66: error: conversion from ‘Display* {aka _XDisplay*}’ to ‘const TCollection_AsciiString’ is **_ambiguous_**
> myDisplay = new Aspect_DisplayConnection (glfwGetX11Display());
> 
> Can someone help me with that. Thanks a lot.

Which OCCT version do you use for building?, `Aspect_DisplayConnection (glfwGetX11Display())` working on OCCT7.4

**Comment by Spaceman007** [comment]
> > Hi, I have installed glfw3.2.1. When I **make**, there are errors:
> > glfw-occt/GlfwOcctWindow.cpp:58:66: error: conversion from ‘Display* {aka _XDisplay*}’ to ‘const TCollection_AsciiString’ is **_ambiguous_**
> > myDisplay = new Aspect_DisplayConnection (glfwGetX11Display());
> > Can someone help me with that. Thanks a lot.
> 
> Which OCCT version do you use for building?, `Aspect_DisplayConnection (glfwGetX11Display())` working on OCCT7.4

Thanks. I was using occt7.3
